apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: pilankar-masale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pilankar-masale
  template:
    metadata:
      labels:
        app: pilankar-masale
    spec:
      containers:
        - name: pilankar-masale
          image: aksdevopsacr.azurecr.io/pilankarmasale
          ports:
            - containerPort: 80
# To schedule pods on Azure Virtual Nodes            
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule 
---
apiVersion: v1
kind: Service
metadata:
  name: pilankar-masale-loadbalancer-service
  labels:
    app: pilankar-masale
spec:
  type: LoadBalancer
  selector:
    app: pilankar-masale
  ports:
    - port: 80
      targetPort: 80


